### ISSUE TITLE
Vario not working with 1773beta - downgraded to 1714beta and it is working again

### ISSUE THREAD

**Issue by edmondscommerce** [fhorinek/SkyDrop#115]
Upgraded from 1278 to 1773beta however the device no longer functioned as a vario - there was no vario readings displayed and the only audio was if weak lift was enabled it would then emit a continuous flat tone.

I've down downgraded to 1714 and the vario functionality is working again. This is the most critical function for me so this is a good solution for now.

I also seem to be having issues with the device no longer appearing as a mass storage device when plugging into the PC (Fedora 22) so had to work with the SD card directly, though not sure if that is just linux playing up.

**Comment by fhorinek** [comment]
1773 is beta release so there might be a few problems with certain devices. The problem you are describing is caused by NaN condition in flight computer. It is fixed right now not yet released.

Please send me the dmesg of after you connect the device, also please describe led status. You can also send debug.log file.

The development is done on linux machines so it should work.

**Comment by ZIRminator** [comment]
Are you able to tell any dates for the new update, so I can decide if I downgrade ore not? Yesterday I had three flights with 1773 and the device was completely useless :( not even vario worked.
I am not trying to rush, just want an info ;)

**Comment by fhorinek** [comment]
next probably beta release will be available in ~2 days

**Comment by fhorinek** [comment]
Updates are out. Please report back it fix your problems.

**Comment by edmondscommerce** [comment]
Hi sorry for delay updating - can confirm latest versions are working nicely
