### ISSUE TITLE
GPS problem

### ISSUE THREAD

**Issue by tomasz13** [fhorinek/SkyDrop#12]
"G" blinking and looking for satellites, but GPS can not connect.

**Comment by philipphuber1** [comment]
My Drop has exactly the same issue. GPS does not get a FIX. "G" keeps blinking. Build 0322 installed.

**Comment by mercutio99** [comment]
I have the same problem...

**Comment by wunderbaresnet** [comment]
yes, it takes forever the first time. what helped with me was turn off and on again. connected then right away.

**Comment by fhorinek** [comment]
Please go to settings->GPS->Status
there is screen with satelits signal monitor

**Comment by petesy** [comment]
At the signal monitor i found  all value are zero and no change after 1 h. no gps  fix.
lon: 0.000  0/0
lat 0.000   0/0
Hdvp: 0.00 0

**Comment by philipphuber1** [comment]
same for me

**Comment by mercutio99** [comment]
same for me

**Comment by fhorinek** [comment]
I am closing this issue, since no one will experience this bug from now.

Some devices from the first batch suffer this bug. It is hardware bug. You need to replace one resistor with 0 Ohm or just solder bridge. If you do not have experience or tools to do that please contact us and we will provide you with the address where you can send your device for repair. 

Everyone who have broken drop should received this message already. 

This component has to be replaced:
![ir_attachment_1019](https://cloud.githubusercontent.com/assets/9072684/8354723/6f71bc70-1b4a-11e5-9b41-09886a189c10.jpeg)
