### ISSUE TITLE
Time zone in logger

### ISSUE THREAD

**Issue by flub** [fhorinek/SkyDrop#255]
Hi,

Thanks for the great vario and continued work on it!  Recently I was looking to find the time zone information in the IGC record but could not find the TNZ H-record in the file.  Would it be possible to add this to the log?

Thanks

**Comment by fhorinek** [comment]
Done, it will be avalible in next release

**Comment by flub** [comment]
Thanks!

Out of curiosity on how/where this is implemented I had a look in src/fc/logger/igc.cpp and was surprised not to see it in the igc_start function.  I also didn't find it with some grepping.  Am I looking in the wrong place for this feature?

**Comment by fhorinek** [comment]
You will have to look inside my work computer since it is not yet pushed
here :)

On 2 Mar 2017 10:15 p.m., "Floris Bruynooghe" <notifications@github.com>
wrote:

Thanks!

Out of curiosity on how/where this is implemented I had a look in
src/fc/logger/igc.cpp and was surprised not to see it in the igc_start
function. I also didn't find it with some grepping. Am I looking in the
wrong place for this feature?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/fhorinek/SkyDrop/issues/255#issuecomment-283783378>,
or mute
the thread

**Comment by fhorinek** [comment]
you can check it now in igc_start

**Comment by flub** [comment]
Thanks for pushing.  I'm slightly surprised to see it write `HTZN` instead of `HFTZN`, it is my understanding that according to A3.2.2 of the spec any H record should always be followed by either `F` (source is the flight recorder and the record is included in G-record checksum) or by `O` (source is other, practically means can be modified as the record is not included in G-record checksum).  Arguably `HO` would be fine for timezone though `HF` is probably more correct.  Anyway, maybe I'm misreading the spec and I don't have any other IGC file which writes the TZN record so can't compare.  Curious as to what your thoughts are.

**Comment by fhorinek** [comment]
I am sorry i forgot the source, it will be included in next release. As **F**light recorder header
