### ISSUE TITLE
Altitude alarm upper limit

### ISSUE THREAD

**Issue by tomasz13** [fhorinek/SkyDrop#348]
It would be good to set the upper limit in the "altitude alarm" menu. If I reach the altitude limit (for example 2500m in slovakia), then I would like to hear the alarm. Is it possible to implement this feature?

**Comment by tomasz13** [comment]
is it problem to implement this feature?

**Comment by bubeck** [comment]
It is very easy. I can offer to do this, if Fero says "OK, go for it".

**Comment by fhorinek** [comment]
Hi til go for it :)

On Sep 22, 2018 13:10, "Dr. Tilmann Bubeck" <notifications@github.com>
wrote:

It is very easy. I can offer to do this, if Fero says "OK, go for it".

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fhorinek/SkyDrop/issues/348#issuecomment-423736651>,
or mute
the thread

**Comment by Fiddich** [comment]
@tomasz13 it is available in the latest firmware
