### ISSUE TITLE
invalid IGC's since Build 5203

### ISSUE THREAD

**Issue by AffiFPV** [fhorinek/SkyDrop#434]
I updated my Skybean yesterday and now all my Tracklogs from today are invalid (on [dhv-xc](https://www.dhv-xc.de/leonardo/index.php?op=show_flight&flightID=1267426) and fai's open validation server). The ones I did two days ago (on Sunday / build 5192) are vaild. [Download on of todays tracks here](https://www.dhv-xc.de/leonardo//data/flights/tracks/2020/13871/04-1240.IGC) (Would have to zip it to upload to github)

**Comment by fhorinek** [comment]
Hi sorry there was a glitch with the G-record signing (different private key was used). The update 5205 is out with the fix.
Since the key is know to me, O was able to correct the record.
Here is your file with updated signature.
[04-1240.zip](https://github.com/fhorinek/SkyDrop/files/4890849/04-1240.zip)

Thank you for the report and sorry for the inconvenience.
