### ISSUE TITLE
BLUETOOTH

### ISSUE THREAD

**Issue by mago73** [fhorinek/SkyDrop#65]
The most important issue is a full compatibility and easy pairing  bluetooth with xc track and flyskyhy ,two of the most important program for android and apple.Sky drop need soon the bluetooth functionality, without this function this variometer loses 50% utility.

**Comment by IB0S** [comment]
Hi! I have another question in this topic.
One of my SkyDrops tells in the Bluetooth menu, that it's "pan1026 v4.0". The other is showing "Unknown". Both are on v789.
Is that a problem? Maybe different BT modules?

**Comment by fhorinek** [comment]
@mago73 
soon, I just came back form the vacation :)

@IB0S  The unknown message means that the module type was not yet detected, since it is not used right now it is not important for the firmware.
If you want to know you can reset factory test.
The module will be auto-detected later when the module will be used.

**Comment by Altgenug1** [comment]
Is the Bluetooth - module you are using, supporting iPhone?
I can see the skydrop on my laptop, but not on my iPhone 4S or on my iPad.
The name of my module is pan 1322 v2.1

**Comment by fhorinek** [comment]
@Altgenug1 module pan1322 is only version 2.1 and it support only standard HCI. Apple refuse to support this protocol. 

pan1026 in newer skydrop versions (shipping from ~2 months ago) support btle and therefore iPhone support is possible.

Currently there is no bt support available. We are working on bt v2.1 support right now.

**Comment by Altgenug1** [comment]
@fhorinek: that sounds bad - I didn`t know that you are changing hardware and we "early birds" (I got my one on 19.6.2015 - so nearly exact 2 month ago) will have some problems using the skydrop together with iPhone or iPad :-(    I bought it exactly for this. 
Is there a possibility to get an update so that it will work (hard- and/or software?)

**Comment by fhorinek** [comment]
I will have to speak with other but we will not forget to our early
adopters. We will find a solution. Maybe board exchange or something like
that.

**Comment by pculka** [comment]
I'm thinking about purchasing SkyDrop exactly due future possibility of pairing with flyskyhy. Gonna have to wait I guess :/

**Comment by SonnenSimon** [comment]
Yes, Bluetooth is also a must feature for me! Is there a rough realisation-date for it?
(Just starting with Paraglyding, iphone4s, discovered flyskyhy & want a bluetooth-vario for it. Almost bought Flynet3, but Skydrop just seems awesome. So I am thinking if i should buy it..)

**Comment by Fischn** [comment]
@fhorinek 
i realised, that i also have the "module pan1322 v2.1" in my early adopters SkyDrop.
Are there any News about your announced solution?

**Comment by Altgenug1** [comment]
Hy!
To your Information:
After installing the 1186beta I am not able to switch it on. I see the starting Monitor for among 1 sec. than the SkyDrop ist switching of by itself. I was able to go back to the 1112beta. This works.
Because the main differenc in the software is the Bluetooth functionality I think maybe the different Bluetooth-chip is the problem.
Do you already have a solution for us "early birds"

**Comment by fhorinek** [comment]
1186 is experimental, the problem with the boot is not related to module.
Booth bluetooth modules will be supported

**Comment by Skywingsmag** [comment]
Received my SkyDrop yesterday. Many thanks! All seems fine except bluetooth. I've tried connecting via my iMac, my Android phone and my iPad, but nothing can see the SkyDrop Bluetooth. The Bluetooth module is pan1026v40. Any ideas?

**Comment by Fischn** [comment]
Hi!
Tried 1186beta because you promised bluetooth connections for both modules.
Still no connection possible on IOS 8 Iphone 5 or IOs 9 Ipad 3.
Any suggestions?

**Comment by fhorinek** [comment]
Hi @Skywingsmag , @Fischn 
currently we are working on rfcomm (SPP) bluetooth profile, iOS does not support this profile. 
Also since 1186beta is experimental release, the bluetooth functionality can be buggy. 
I expect to release more stable release with working bluetooth support in few days. After that I will look on BTLE bluetooth profile for iOS.

**Comment by Skywingsmag** [comment]
Hi, Fhorinek,

Thanks for your reply. Look forward to the update.

Best regards, Colin.

SKYWINGS MAGAZINE design, production & advertising department
www.skywingsmag.com

**Comment by fhorinek** [comment]
The Bluetooth is now available for android devices.

**Comment by sqltuning** [comment]
Hi fhorinek,
don't you have any updates about BT for iOS ?
Thanks a lot
Jan

**Comment by fhorinek** [comment]
sorry no btle support is currently available, we are working on logging now

**Comment by SonnenSimon** [comment]
what a pity..
(If I can use skydrop with flyskyhy on iOs I don't really need skydrops own logging..)
hopefully btle support will come soon!

**Comment by Fischn** [comment]
Have you stopped your plans für iOS support, or why did you closed this topic.
Installed 1714beta today. Still have no iOS connectivity

**Comment by fhorinek** [comment]
@Fischn this is not a task issue, it was only a question. I was cleaning the issues.
I am still working on iOS support. 
do no worry
