### ISSUE TITLE
zero lift tone

### ISSUE THREAD

**Issue by filozof83** [fhorinek/SkyDrop#70]
hi,
maybe you can implement a specific tone to indicate zero lift. some varios have that function and in some cases it's helpful.
thx

**Comment by tomasz13** [comment]
do you mean something like flymaster's  "buzzer sound" function?

"Buzzer Sound which is produced when the rate of climb is close to, but has not yet reached the specified Climb threshold. Since the Buzzer starts earlier than the normal vario sound is an amazing companion in flight allowing the pilot to pick-up thermals he would have usually missed."

**Comment by filozof83** [comment]
exactly! lebip calls it "lifty air detector" and it should be switchable.

**Comment by fhorinek** [comment]
implemented in next release
